# Generated by Django 4.2 on 2024-02-22 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, verbose_name='Временная метка'),
        ),
    ]
