# Generated by Django 4.2 on 2024-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_message_alter_mailinglog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
    ]
